/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificadorRouteImport } from './routes/verificador'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'

const VerificadorRoute = VerificadorRouteImport.update({
  id: '/verificador',
  path: '/verificador',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/busca' | '/fabrica' | '/ranking' | '/verificador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busca' | '/fabrica' | '/ranking' | '/verificador'
  id: '__root__' | '/' | '/busca' | '/fabrica' | '/ranking' | '/verificador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  FabricaRoute: typeof FabricaRoute
  RankingRoute: typeof RankingRoute
  VerificadorRoute: typeof VerificadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificador': {
      id: '/verificador'
      path: '/verificador'
      fullPath: '/verificador'
      preLoaderRoute: typeof VerificadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  FabricaRoute: FabricaRoute,
  RankingRoute: RankingRoute,
  VerificadorRoute: VerificadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
