/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificadorRouteImport } from './routes/verificador'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedRegistrarRouteImport } from './routes/_authenticated/registrar'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'

const VerificadorRoute = VerificadorRouteImport.update({
  id: '/verificador',
  path: '/verificador',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrarRoute = AuthenticatedRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/registrar': typeof AuthenticatedRegistrarRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/contratos'
    | '/creditos'
    | '/obras'
    | '/painel'
    | '/perfil'
    | '/portfolio'
    | '/registrar'
    | '/seguranca'
    | '/portfolio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/contratos'
    | '/creditos'
    | '/obras'
    | '/painel'
    | '/perfil'
    | '/portfolio'
    | '/registrar'
    | '/seguranca'
    | '/portfolio/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/_authenticated/contratos'
    | '/_authenticated/creditos'
    | '/_authenticated/obras'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/portfolio'
    | '/_authenticated/registrar'
    | '/_authenticated/seguranca'
    | '/portfolio/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  FabricaRoute: typeof FabricaRoute
  RankingRoute: typeof RankingRoute
  VerificadorRoute: typeof VerificadorRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificador': {
      id: '/verificador'
      path: '/verificador'
      fullPath: '/verificador'
      preLoaderRoute: typeof VerificadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrar': {
      id: '/_authenticated/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof AuthenticatedRegistrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRegistrarRoute: typeof AuthenticatedRegistrarRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRegistrarRoute: AuthenticatedRegistrarRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  FabricaRoute: FabricaRoute,
  RankingRoute: RankingRoute,
  VerificadorRoute: VerificadorRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
