/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificadorRouteImport } from './routes/verificador'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegistrarRouteImport } from './routes/_authenticated/registrar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'

const VerificadorRoute = VerificadorRouteImport.update({
  id: '/verificador',
  path: '/verificador',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistrarRoute = AuthenticatedRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/fabrica': typeof FabricaRoute
  '/ranking': typeof RankingRoute
  '/verificador': typeof VerificadorRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/registrar': typeof AuthenticatedRegistrarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/obras'
    | '/painel'
    | '/perfil'
    | '/registrar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/obras'
    | '/painel'
    | '/perfil'
    | '/registrar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/busca'
    | '/cadastro'
    | '/entrar'
    | '/fabrica'
    | '/ranking'
    | '/verificador'
    | '/_authenticated/obras'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/registrar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  FabricaRoute: typeof FabricaRoute
  RankingRoute: typeof RankingRoute
  VerificadorRoute: typeof VerificadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificador': {
      id: '/verificador'
      path: '/verificador'
      fullPath: '/verificador'
      preLoaderRoute: typeof VerificadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registrar': {
      id: '/_authenticated/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof AuthenticatedRegistrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRegistrarRoute: typeof AuthenticatedRegistrarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRegistrarRoute: AuthenticatedRegistrarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  FabricaRoute: FabricaRoute,
  RankingRoute: RankingRoute,
  VerificadorRoute: VerificadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
